#include "..\components\c_battle_stats.h"

const char gTypeNames[NUM_TYPES + 1][TYPE_NAME_LENGTH + 1] = {
    [TYPE_NORMAL]   = "NORMAL",
    [TYPE_FIRE]     = "FIRE",
    [TYPE_WATER]    = "WATER",
    [TYPE_ELECTRIC] = "ELECTRIC",
    [TYPE_GRASS]    = "GRASS",
    [TYPE_ICE]      = "ICE",
    [TYPE_FIGHTING] = "FIGHTING",
    [TYPE_POISON]   = "POISON",
    [TYPE_GROUND]   = "GROUND",
    [TYPE_FLYING]   = "FLYING",
    [TYPE_PSYCHIC]  = "PSYCHIC",
    [TYPE_BUG]      = "BUG",
    [TYPE_ROCK]     = "ROCK",
    [TYPE_GHOST]    = "GHOST",
    [TYPE_DRAGON]   = "DRAGON",
    [TYPE_DARK]     = "DARK",
    [TYPE_STEEL]    = "STEEL",
    [TYPE_FAIRY]    = "FAIRY",
    [TYPE_NONE]     = "NONE",
};

//most entries in this table are not complete.
//keeping here b/c i can't decide which formatting option i like better.
//Row is attacking type, column is defending type
// const u8 gTypeEffectiveness[NUM_TYPES][NUM_TYPES] = {
//     //                      NOR   FIR   WAT   ELE   GRA   ICE   FIG   POI   GRO   FLY   PSY   BUG   ROC   GHO   DRA   DAR   STE   FAI
//         [TYPE_NORMAL]   = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, HALF, NONE, NORM, NORM, HALF, NONE },
//         [TYPE_FIRE]     = { NORM, HALF, HALF, NORM, SUPR, SUPR, NORM, NORM, NORM, NORM, NORM, SUPR, HALF, NORM, HALF, NORM, SUPR, NONE },
//         [TYPE_WATER]    = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_ELECTRIC] = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_GRASS]    = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_ICE]      = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_FIGHTING] = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_POISON]   = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_GROUND]   = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_FLYING]   = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_PSYCHIC]  = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_BUG]      = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_ROCK]     = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_GHOST]    = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_DRAGON]   = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_DARK]     = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_STEEL]    = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//         [TYPE_FAIRY]    = { NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM, NORM },
//     };

//stole this from pokeplatinum:
// #define X(__d) MT_##__d##_X
// #define ______ X(1_0)

// enum MoveTesterMatchup {
//     MT_1_0_X = 0, // Regularly effective  1.0x
//     MT_2_0_X = 1, // Super effective      2.0x
//     MT_0_5_X = -1, // Not very effective   0.5x
//     MT_0_0_X = -10, // Not effective        0.0x
// };

// // clang-format off
// static const s8 sMoveTesterTypeChart[NUM_POKEMON_TYPES][NUM_POKEMON_TYPES] =
// { //                                                                                Defending Type
//                     //  Normal Fighting Flying  Poison  Ground  Rock    Bug    Ghost    Steel   Mystery Fire    Water   Grass  Electric Psychic Ice     Dragon  Dark
//   // Attacking Type
//     [TYPE_NORMAL]   = { ______, ______, ______, ______, ______, X(0_5), ______, X(0_0), X(0_5), ______, ______, ______, ______, ______, ______, ______, ______, ______ },
//     [TYPE_FIGHTING] = { X(2_0), ______, X(0_5), X(0_5), ______, X(2_0), X(0_5), X(0_0), X(2_0), ______, ______, ______, ______, ______, X(0_5), X(2_0), ______, X(2_0) },
//     [TYPE_FLYING]   = { ______, X(2_0), ______, ______, ______, X(0_5), X(2_0), ______, X(0_5), ______, ______, ______, X(2_0), X(0_5), ______, ______, ______, ______ },
//     [TYPE_POISON]   = { ______, ______, ______, X(0_5), X(0_5), X(0_5), ______, X(0_5), X(0_0), ______, ______, ______, X(2_0), ______, ______, ______, ______, ______ },
//     [TYPE_GROUND]   = { ______, ______, X(0_0), X(2_0), ______, X(2_0), X(0_5), ______, X(2_0), ______, X(2_0), ______, X(0_5), X(2_0), ______, ______, ______, ______ },
//     [TYPE_ROCK]     = { ______, X(0_5), X(2_0), ______, X(0_5), ______, X(2_0), ______, X(0_5), ______, X(2_0), ______, ______, ______, ______, X(2_0), ______, ______ },
//     [TYPE_BUG]      = { ______, X(0_5), X(0_5), X(0_5), ______, ______, ______, X(0_5), X(0_5), ______, X(0_5), ______, X(2_0), ______, X(2_0), ______, ______, X(2_0) },
//     [TYPE_GHOST]    = { X(0_0), ______, ______, ______, ______, ______, ______, X(2_0), X(0_5), ______, ______, ______, ______, ______, X(2_0), ______, ______, X(0_5) },
//     [TYPE_STEEL]    = { ______, ______, ______, ______, ______, X(2_0), ______, ______, X(0_5), ______, X(0_5), X(0_5), ______, X(0_5), ______, X(2_0), ______, ______ },
//     [TYPE_MYSTERY]  = { ______, ______, ______, ______, ______, ______, ______, ______, ______, ______, ______, ______, ______, ______, ______, ______, ______, ______ },
//     [TYPE_FIRE]     = { ______, ______, ______, ______, ______, X(0_5), X(2_0), ______, X(2_0), ______, X(0_5), X(0_5), X(2_0), ______, ______, X(2_0), X(0_5), ______ },
//     [TYPE_WATER]    = { ______, ______, ______, ______, X(2_0), X(2_0), ______, ______, ______, ______, X(2_0), X(0_5), X(0_5), ______, ______, ______, X(0_5), ______ },
//     [TYPE_GRASS]    = { ______, ______, X(0_5), X(0_5), X(2_0), X(2_0), X(0_5), ______, X(0_5), ______, X(0_5), X(2_0), X(0_5), ______, ______, ______, X(0_5), ______ },
//     [TYPE_ELECTRIC] = { ______, ______, X(2_0), ______, X(0_0), ______, ______, ______, ______, ______, ______, X(2_0), X(0_5), X(0_5), ______, ______, X(0_5), ______ },
//     [TYPE_PSYCHIC]  = { ______, X(2_0), ______, X(2_0), ______, ______, ______, ______, X(0_5), ______, ______, ______, ______, ______, X(0_5), ______, ______, X(0_0) },
//     [TYPE_ICE]      = { ______, ______, X(2_0), ______, X(2_0), ______, ______, ______, X(0_5), ______, X(0_5), X(0_5), X(2_0), ______, ______, X(0_5), X(2_0), ______ },
//     [TYPE_DRAGON]   = { ______, ______, ______, ______, ______, ______, ______, ______, X(0_5), ______, ______, ______, ______, ______, ______, ______, X(2_0), ______ },
//     [TYPE_DARK]     = { ______, X(0_5), ______, ______, ______, ______, ______, X(2_0), X(0_5), ______, ______, ______, ______, ______, X(2_0), ______, ______, X(0_5) }
// };
// // clang-format on

// #undef X
// #undef ______

//format is attacking type, then defending type
const u8 gTypeEffectiveness[NUM_TYPES][NUM_TYPES] = {
    [TYPE_NORMAL] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_HALF,
        [TYPE_GHOST]    = TYPE_MULT_NONE,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_FIRE] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_HALF,
        [TYPE_WATER]    = TYPE_MULT_HALF,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_SUPR,
        [TYPE_ICE]      = TYPE_MULT_SUPR,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_SUPR,
        [TYPE_ROCK]     = TYPE_MULT_HALF,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_HALF,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_SUPR,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_WATER] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_SUPR,
        [TYPE_WATER]    = TYPE_MULT_HALF,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_HALF,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_SUPR,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_SUPR,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_HALF,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_NORM,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_ELECTRIC] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_SUPR,
        [TYPE_ELECTRIC] = TYPE_MULT_HALF,
        [TYPE_GRASS]    = TYPE_MULT_HALF,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_NONE,
        [TYPE_FLYING]   = TYPE_MULT_SUPR,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_HALF,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_NORM,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_GRASS] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_HALF,
        [TYPE_WATER]    = TYPE_MULT_SUPR,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_HALF,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_HALF,
        [TYPE_GROUND]   = TYPE_MULT_SUPR,
        [TYPE_FLYING]   = TYPE_MULT_HALF,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_HALF,
        [TYPE_ROCK]     = TYPE_MULT_SUPR,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_HALF,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_ICE] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_HALF,
        [TYPE_WATER]    = TYPE_MULT_HALF,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_SUPR,
        [TYPE_ICE]      = TYPE_MULT_HALF,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_SUPR,
        [TYPE_FLYING]   = TYPE_MULT_SUPR,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_SUPR,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_FIGHTING] = {
        [TYPE_NORMAL]   = TYPE_MULT_SUPR,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_SUPR,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_HALF,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_HALF,
        [TYPE_PSYCHIC]  = TYPE_MULT_HALF,
        [TYPE_BUG]      = TYPE_MULT_HALF,
        [TYPE_ROCK]     = TYPE_MULT_SUPR,
        [TYPE_GHOST]    = TYPE_MULT_NONE,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_SUPR,
        [TYPE_STEEL]    = TYPE_MULT_SUPR,
        [TYPE_FAIRY]    = TYPE_MULT_HALF,
    },
    [TYPE_POISON] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_SUPR,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_HALF,
        [TYPE_GROUND]   = TYPE_MULT_HALF,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_HALF,
        [TYPE_GHOST]    = TYPE_MULT_HALF,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_NONE,
        [TYPE_FAIRY]    = TYPE_MULT_SUPR,
    },
    [TYPE_GROUND] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_SUPR,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_SUPR,
        [TYPE_GRASS]    = TYPE_MULT_HALF,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_SUPR,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NONE,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_HALF,
        [TYPE_ROCK]     = TYPE_MULT_SUPR,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_SUPR,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_FLYING] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_HALF,
        [TYPE_GRASS]    = TYPE_MULT_SUPR,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_SUPR,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_SUPR,
        [TYPE_ROCK]     = TYPE_MULT_HALF,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_PSYCHIC] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_SUPR,
        [TYPE_POISON]   = TYPE_MULT_SUPR,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_HALF,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_NONE,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_BUG] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_HALF,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_SUPR,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_HALF,
        [TYPE_POISON]   = TYPE_MULT_HALF,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_HALF,
        [TYPE_PSYCHIC]  = TYPE_MULT_SUPR,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_HALF,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_SUPR,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_HALF,
    },
    [TYPE_ROCK] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_SUPR,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_SUPR,
        [TYPE_FIGHTING] = TYPE_MULT_HALF,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_HALF,
        [TYPE_FLYING]   = TYPE_MULT_SUPR,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_SUPR,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_GHOST] = {
        [TYPE_NORMAL]   = TYPE_MULT_NONE,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_SUPR,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_SUPR,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_HALF,
        [TYPE_STEEL]    = TYPE_MULT_NORM,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
    [TYPE_DRAGON] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_SUPR,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_NONE,
    },
    [TYPE_DARK] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_NORM,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_HALF,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_SUPR,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_SUPR,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_HALF,
        [TYPE_STEEL]    = TYPE_MULT_NORM,
        [TYPE_FAIRY]    = TYPE_MULT_HALF,
    },
    [TYPE_STEEL] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_HALF,
        [TYPE_WATER]    = TYPE_MULT_HALF,
        [TYPE_ELECTRIC] = TYPE_MULT_HALF,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_SUPR,
        [TYPE_FIGHTING] = TYPE_MULT_NORM,
        [TYPE_POISON]   = TYPE_MULT_NORM,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_SUPR,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_NORM,
        [TYPE_DARK]     = TYPE_MULT_NORM,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_SUPR,
    },
    [TYPE_FAIRY] = {
        [TYPE_NORMAL]   = TYPE_MULT_NORM,
        [TYPE_FIRE]     = TYPE_MULT_HALF,
        [TYPE_WATER]    = TYPE_MULT_NORM,
        [TYPE_ELECTRIC] = TYPE_MULT_NORM,
        [TYPE_GRASS]    = TYPE_MULT_NORM,
        [TYPE_ICE]      = TYPE_MULT_NORM,
        [TYPE_FIGHTING] = TYPE_MULT_SUPR,
        [TYPE_POISON]   = TYPE_MULT_HALF,
        [TYPE_GROUND]   = TYPE_MULT_NORM,
        [TYPE_FLYING]   = TYPE_MULT_NORM,
        [TYPE_PSYCHIC]  = TYPE_MULT_NORM,
        [TYPE_BUG]      = TYPE_MULT_NORM,
        [TYPE_ROCK]     = TYPE_MULT_NORM,
        [TYPE_GHOST]    = TYPE_MULT_NORM,
        [TYPE_DRAGON]   = TYPE_MULT_SUPR,
        [TYPE_DARK]     = TYPE_MULT_SUPR,
        [TYPE_STEEL]    = TYPE_MULT_HALF,
        [TYPE_FAIRY]    = TYPE_MULT_NORM,
    },
};

const BattleMove gBattleMoves[MOVES_COUNT] = {
    [MOVE_NONE] = {
        .effect = EFFECT_HIT,
        .power = 0,
        .type = TYPE_NORMAL,
        .accuracy = 0,
        .pp = 0,
        .secondaryEffectChance = 0,
        .target = MOVE_TARGET_SELECTED,
        .priority = 0,
        .flags = 0,
    },
    [MOVE_POUND] = {
        .effect = EFFECT_HIT,
        .power = 40,
        .type = TYPE_NORMAL,
        .accuracy = 100,
        .pp = 35,
        .secondaryEffectChance = 0,
        .target = MOVE_TARGET_SELECTED,
        .priority = 0,
        .flags =
            FLAG_MAKES_CONTACT
            | FLAG_PROTECT_AFFECTED
            | FLAG_MIRROR_MOVE_AFFECTED
            | FLAG_KINGS_ROCK_AFFECTED,
    },
    [MOVE_HYDRO_STEAM] = {
        .effect = EFFECT_HIT,
        .power = 40,
        .type = TYPE_NORMAL,
        .accuracy = 100,
        .pp = 35,
        .secondaryEffectChance = 0,
        .target = MOVE_TARGET_SELECTED,
        .priority = 0,
        .flags =
            FLAG_MAKES_CONTACT
            | FLAG_PROTECT_AFFECTED
            | FLAG_MIRROR_MOVE_AFFECTED
            | FLAG_KINGS_ROCK_AFFECTED,
    },
};